alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "jenkins"
    metrics_path: /prom/
    static_configs:
      - targets: ["ec2-3-0-52-164.ap-southeast-1.compute.amazonaws.com:9000"]
