node {
    stage('Build') {
        // Menggunakan Docker image 'python:2-alpine' untuk build
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        // Menggunakan Docker image 'qnib/pytest' untuk test
        docker.image('qnib/pytest').inside {
            try {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            } finally {
                // Menggunakan junit untuk mempublikasikan hasil test
                junit 'test-reports/results.xml'
            }
        }
    }

    stage('Deliver') {
        // Menggunakan Docker image 'cdrx/pyinstaller-linux:python2' untuk deliver
        docker.image('cdrx/pyinstaller-linux:python2').inside {
            sh 'pyinstaller --onefile sources/add2vals.py'
        }
        // Mengarsipkan artifact hasil build
        archiveArtifacts 'dist/add2vals'
    }
}
