properties([
    pipelineTriggers([
        pollSCM('H/2 * * * *')
    ])
])

node {
    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        docker.image('python:2-alpine').inside {

            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            try {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            } finally {
                junit 'test-reports/results.xml'
            }
        }
    }
    stage('Approval'){
        def userInput = input(
            message: "Lanjutkan ke tahap Deploy?",
            ok: "Submit",
            parameters: [choice(name: 'Approval', choices: 'Yes\nNo', description: 'Setujui atau hentikan pipeline')]
        )
        if (userInput == 'No') {
            echo "Approval tidak didiberikan..."
            error("Pipeline dihentikan oleh pengguna.")
        } else {
            echo "Approval diberikan, melanjutkan ke tahap Deploy..."
        }

    }

    stage('Deliver') { /* harus deploy*/
        docker.image('python:3-alpine').inside('-u root') { // Run as root inside the container
            sh '''
            apk add --no-cache binutils
            pip install --no-cache-dir pyinstaller
            pyinstaller --onefile sources/add2vals.py
        '''
        }

        echo "Pausing for 1 minute before archiving artifacts..."
        sleep 60
        echo "Resuming pipeline after 1-minute pause."
        archiveArtifacts artifacts: 'dist/add2vals', onlyIfSuccessful: false
    }
}
